socat/Dockerfile

ship it already

---

gcloud/helm/Dockerfile

A container with the helm client installed, to be used for doing helm-based deploys of kubernetes services.

Container for doing helm deploys

---

gcloud/helm/Dockerfile

Remove install of make, do helm client init so stable repo is available by default.

Do helm client init so stable charts repo is available.

---

golang/unit_tests.sh

The `unit_tests.sh` script was returning zero even when a test was failing.  Since we use this script in the ssh-gateway pipeline, I would like the build to fail if a test fails.
- change from `/bin/sh` to `/bin/bash` so we can use `PIPESTATUS`
- added test return code variable (`TEST_RC`)
- `TEST_RC` is set to non-zero if any test fails
- replaced a stray tab with spaces to match the other indentation
- capture `PIPESTATUS` in a temporary `LAST_RC` variable.  This is because of the following:
```
if [[ ${PIPESTATUS[0]} != 0 ]] ; then  # previous pipe failed....
TEST_RC=${PIPESTATUS[0]}           # So status is back to zero
fi
```

Preserve exit status of test

---

linters/yamllint/README.md

.yamllint should be .yamllintrc in the README.

Fix incorrect file name.

---

linters/pylint/.pylintrc
linters/pylint/Dockerfile
linters/pylint/README.md
linters/pylint/bin/run_pylint.sh

EET-4369: Create pylint image to use when linting python code.

---

packer/Dockerfile
packer/README.md

Mostly this is just [Hashicorp's packer image](https://hub.docker.com/r/hashicorp/packer/) but with docker.

Initial packer image 🐣

---

gcloud/terraform/Dockerfile

Figure we should do a bit more legwork to make sure we received the binary we intended.

Verify Terraform SHA256sum

---

golang/Dockerfile

Update our image to Go 1.9 (currently 1.9.1) and install dep.

Update to 1.9 and install dep

---

newrelic-php-daemon/7.6.0.201/Dockerfile
newrelic-php-daemon/README.md

* Added a New Relic PHP daemon image pinned to a specific NR daemon release

CMWP-1924 - Added New Relic PHP daemon image

---

Jenkinsfile

Publish our iptables image to our private registries.

Publish iptables to gcr

---

gotpl/Dockerfile
gotpl/README.md

Adding gotpl image.
```
cat vars.yml | docker run -i --rm -v ${PWD}:/src -w /src wpengine/gotpl ./Dockerfile.gotpl > Dockerfile
```
cc: @hkz-aarvesen @anneal

Adding gotpl image.

---

golang/Dockerfile

Update golang image to 1.10

---

linters/flake8/.flake8

All wildcards to the django project file paths we would like to exclude

Wildcard django project files path

---

local-dev/5.6/Dockerfile
local-dev/5.6/entrypoint.sh
local-dev/7.0/Dockerfile
local-dev/7.0/entrypoint.sh
local-dev/7.1/Dockerfile
local-dev/7.1/entrypoint.sh
local-dev/7.2/Dockerfile
local-dev/7.2/entrypoint.sh
local-dev/README.md

Adds images for local-dev use in PHP 5.6-7.2
I'm really not sure of the architecture here so if I'm doing this wrong I'm up for ideas.

Add local-dev images

---

local-dev/5.6/Dockerfile
local-dev/5.6/entrypoint.sh
local-dev/7.0/Dockerfile
local-dev/7.0/entrypoint.sh
local-dev/7.1/Dockerfile
local-dev/7.1/entrypoint.sh
local-dev/7.2/Dockerfile
local-dev/7.2/entrypoint.sh

We need to use the host user for PHP to avoid issues. This will set it
on startup using appropriate ARGs

Set PHP to host user

---

linters/phpcs/README.md

Adding more info to the phpcbf readme

Adding how-to guide for running PHPCBF

---

local-dev/7.0/Dockerfile

In troubleshooting earlier I had mistakenly forgotten to reintroduce VIM and SVN.

Reintroduce VIM and SVN

---

gcloud/terraform/Dockerfile

Update to latest stable release.

Update Terraform to 0.11.8

---

local-dev/5.6/Dockerfile
local-dev/5.6/xdebug-listen-off.sh
local-dev/5.6/xdebug-listen-on.sh
local-dev/5.6/xdebug.ini
local-dev/7.0/Dockerfile
local-dev/7.0/xdebug-listen-off.sh
local-dev/7.0/xdebug-listen-on.sh
local-dev/7.0/xdebug.ini
local-dev/7.1/Dockerfile
local-dev/7.1/xdebug-listen-off.sh
local-dev/7.1/xdebug-listen-on.sh
local-dev/7.1/xdebug.ini
local-dev/7.2/Dockerfile
local-dev/7.2/xdebug-listen-off.sh
local-dev/7.2/xdebug-listen-on.sh
local-dev/7.2/xdebug.ini

Adds XDebug and supporting configuration files.

Local dev xdebug

---

local-dev/5.6/entrypoint.sh
local-dev/7.0/entrypoint.sh
local-dev/7.1/entrypoint.sh
local-dev/7.2/entrypoint.sh

This will let us access xdebug information more easily and will do so in Linux.

Reset the /data directory for xdebug logs

---

golang/Dockerfile

Adding protobuf compiler and GRPC to our golang image to support client/server code generation.

Add protobuf/grpc support

---

apigee-test-shared/Dockerfile
apigee-test-shared/README.md
apigee-test-shared/package-lock.json
apigee-test-shared/package.json
apigee-test-shared/test.sh

Our intention is to create a new dockerhub image that will be used to test our Apigee proxies

OCT-241 Added new folder: api-test-shared

---

ansible/Dockerfile
ansible/README.md

Add molecule to this image (which I don't believe is in active use at the moment).

[SRE-3264] Add molecule

---

iptables/Dockerfile
iptables/README.md

OBSV-2210 Delete iptables base images

---

.github/CODEOWNERS

PINS-315 updating CODEOWNERS to new team

PINS-315 updating CODEOWNERS to new team
