wpengine/base-images-public

- golang/Dockerfile
This adds [gometalinter](https://github.com/alecthomas/gometalinter) and [glide](https://github.com/Masterminds/glide) to the offical golang image.  I'm going to set it up as a public automated docker build so that we don't have to add these dependencies to every pipeline and we can track upstream.
We're building from the [Debian buildpack](https://hub.docker.com/_/buildpack-deps/) golang image since that makes a better general build tool than the alpine images.
> Add golang image

- gcloud/terraform/Dockerfile
The hasicorp/terraform image doesn't have gcloud (or kubectl) available
which means the kubernetes provider doesn't work.
> Add new terraform public image

- golang/Dockerfile
- golang/unit_tests.sh
In support of CMWP-1336, we need to add better coverage and test tooling to our 'builder' image.
> Add unit_tests script as entrypoint, add go package for better coverage and junit output

- golang/unit_tests.sh
Jenkins build is failing trying to parse the cobertura XML.  This is due to trying to use an outdated URL for the cobertura DTD.
This checkin replaces the old busted URL with a valid URL. This has been the valid URL, apparently, since 2013 https://github.com/cobertura/cobertura/issues/38
Here's what's output"
```
<!DOCTYPE coverage SYSTEM "https://raw.github.com/cobertura/cobertura/master/cobertura/src/site/htdocs/xml/coverage-03.dtd">
```
Before
```
$ groovy -classpath /Users/alan.arvesen/dev/lib/java/dom4j/dom4j-2.0.2.jar tmp.groovy 
Caught: org.dom4j.DocumentException: Connection reset
org.dom4j.DocumentException: Connection reset
at org.dom4j.io.SAXReader.read(SAXReader.java:468)
at org.dom4j.io.SAXReader.read(SAXReader.java:307)
at org.dom4j.io.SAXReader$read.call(Unknown Source)
at …
```
> Rename outdated DTD URL

- gcloud/terraform/Dockerfile
Would like to move to terraform v0.10.7 now that it is released. Specifically for the following bug fix:
> modules: Fix regression in the handling of modules sourcing other modules with relative paths (#16160)
> Bump Terraform Version

- LICENSE
- README.md
- gcloud/README.md
- gcloud/helm/README.md
- gcloud/kubectl-make/README.md
- gcloud/terraform/README.md
- golang/README.md
- socat/README.md
The readme in the base of this repository ended up as the default for a handful of the images on Docker Hub. This PR:
* Massages the repo's readme
* Adds a readme for any subdirectory/image that did not already have one
* Includes the MIT license
> Expanded Documentation

- ansible/Dockerfile
- ansible/README.md
- ansible/initctl_faker
Adding a generic ansible image. My imagined use cases are:
* As a base image when validating packer templates using the docker builder + ansible provisioners
* Running testinfra tests inside the resulting packer-produced image
* ansible-lint in a container
> Initial ansible lint and test image

- fluentd/Dockerfile
- fluentd/README.md
- fluentd/fluent.conf
- fluentd/plugins/.gitignore
Extending fluent's fluentd image per their documentation at: https://github.com/fluent/fluentd-docker-image/blob/master/README.md#how-to-build-your-own-image
The included fluent.conf is a copy/paste job from their repo. In most cases, we'd be providing our own config along with the `FLUENTD_CONF` env var at runtime.
> Add Fluentd Image

- gcloud/docker/Dockerfile
- gcloud/docker/README.md
Creating our own docker image built on google/cloud-sdk with docker-engine installed.
> [EET-4592] Adding docker image with gcloud and docker

- linters/shellcheck/Dockerfile
- linters/shellcheck/README.md
Adding a copy of the "official" [shellcheck docker image](https://github.com/koalaman/shellcheck/blob/master/Dockerfile) to our organization's repo so we can ensure the contents of the image.
> Mirror shellcheck image

- golang/unit_tests.sh
The JUnit reports in our [Jenkins build](https://jenkins.wpengine.io/job/WPEngineGitHubRepos/job/ssh-gateway/job/master/306/consoleText) aren't generated because of the following error:
```
stat /go/src/github.com/jstemmer/go-junit-report/junit-formatter.go: no such file or directory
```
This PR attempts to resolve that, see this convo from `Jenkins Guild` on 3/19 for details:
```
[3:31 PM] Eric Haase: getting the following error in our build https://jenkins.wpengine.io/job/WPEngineGitHubRepos/job/ssh-gateway/job/master/306/ :
[3:31 PM] Eric Haase:
stat /go/src/github.com/jstemmer/go-junit-report/junit-formatter.go: no such file or directory
[3:32 PM] Eric Haase: which should be included in our docker image according to https://hub.docker.com/r/wpengine/golang/~/dockerfile/
[3:32 PM] Eric …
```
> NOJIRA: Remove redundant junit-formatter param

- squid/Dockerfile
- squid/squid.conf
The cache dir was mismatched between the env vars set in the Dockerfile and squid.conf causing squid to crash on start.
> Fix cache dir mismatch

- linters/flake8/.flake8
- linters/flake8/Dockerfile
- linters/flake8/README.md
This PR adds a minimal flake8 image. We are moving away from pylint back to flake8 and there are some situations where it can be nice to have a standalone flake8 image available.
> Add minimal flake8 image

- golang/Dockerfile
Updates to Go version 1.11 in order to make use of newer features, particularly native modules support.
> Update to Go 1.11

- linters/phpcs/Dockerfile
- linters/phpcs/README.md
- linters/phpcs/composer.json
A minimal `phpcs` image useful for linting PHP files.
This image supports linting for WordPress Core Standards, PHP Compatibility, and any library provided by [phpcs](https://github.com/squizlabs/PHP_CodeSniffer) including PSR-2.
1. `cd` into the phpcs dir
2. Run `docker build --tag phpcs .`
3. Navigate to a PHP project and run any of the following commands:
```
docker run --rm -v `pwd`:/workspace phpcs /workspace --standard=PHPCompatibility --runtime-set testVersion 7.2-
```
```
docker run --rm -v `pwd`:/workspace phpcs /workspace --standard=WordPress
```
```
docker run --rm -v `pwd`:/workspace phpcs /workspace --standard=PSR2
```
```
docker run --rm -v `pwd`:/workspace phpcs /workspace --standard=./phpcs.xml
```
> [CSI-554] Add phpcs linter

- README.md
- wp-cli/Dockerfile
- wp-cli/README.md
- wp-cli/composer.sh
Adding the core of a wp-cli image we've been using for another project that stopped being built. The older built version on DockerHub needs updated. :)
> Add wp-cli alpine image.

- fluentd/Dockerfile
v 1.2.0 pulled from td-agent/Gemfile-3.lock in server-cm
> pin fluentd bq plugin to the version we use on the farm

- local-dev/5.6/Dockerfile
- local-dev/5.6/xdebug-off.sh
- local-dev/5.6/xdebug-on.sh
- local-dev/7.0/Dockerfile
- local-dev/7.0/xdebug-off.sh
- local-dev/7.0/xdebug-on.sh
- local-dev/7.1/Dockerfile
- local-dev/7.1/xdebug-off.sh
- local-dev/7.1/xdebug-on.sh
- local-dev/7.2/Dockerfile
- local-dev/7.2/xdebug-off.sh
- local-dev/7.2/xdebug-on.sh
Just specifying "lts" doesn't work for whatever reason and, bumping this periodically gives us a good excuse to update the images anyway for any upstream changes.
> Update default node versions.

- fpm/Dockerfile
Debian Jessie mirrors have done shifted on us, so moving this image to use Stretch instead:
see: https://jenkins.wpengine.io/blue/organizations/jenkins/WPEngineGitHubRepos%2Fpear-shaped/detail/PR-16/1/pipeline
```
Step 1/7 : FROM wpengine/fpm
---> 8485ec821208
Step 2/7 : MAINTAINER "WP Engine Tech Ops Team <techops@wpengine.com>"
---> Running in c0682312975a
Removing intermediate container c0682312975a
---> 987f909940dc
Step 3/7 : RUN apt update && apt install -y php-pear apt-transport-https
---> Running in 902b8f76f38c
WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Get:2 http://deb.debian.org jessie-updates InRelease [7340 B]
Get:3 …
```
> Use stretch so we get working apt sources

- golang/Dockerfile
- golang/README.md
**[JIRA ticket](https://wpengine.atlassian.net/browse/COE-1306)**
Gometalinter has been deprecated and was archived on April 7th of this year, so this PR installs golangci-lint into the base image so that services using this base image can start switching over (i.e. the edge-agent) to be able to use an updated (and faster) linter 🎉
> [COE-1306] add golangci-lint to base golang image

- gcloud/terraform/Dockerfile
Hashicorp signing key was exfiltrated.  0.11.15 uses the replacement key to validate module signatures during init
https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512
https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570
> update to latest in 0.11 series

- ubuntu/README.md
- ubuntu/docker/Dockerfile
- ubuntu/docker/README.md
- ubuntu/docker/google-cloud-sdk.list
This adds a Docker image that includes the Docker, Google Cloud CLI, and AWS CLI packages which should update all these packages with a simple rebuild.
> [SRE-8391] Adding docker image with gcloud and awscli

- ubuntu/docker/Dockerfile
It turns out that the `awscliv2` in `pip` is an unofficial wrapper that falls back to Docker under many circumstances. This switches to using the ZIP file approach from the official AWS docs.
> [SRE-8448] Switch to official AWS CLI v2

- fpm/Dockerfile
Ruby 2.4 went EOL 2020-03-31.
Debian stretch went EOL 2020-07-06.
I disagre with pinning FPM to 1.11, but I have confirmed that it is functional under Ruby 2.7, which is where this tag currently points.
> fix: FPM image pinned to EOL ruby and debian

- ansible/Dockerfile
Using Golden ubuntu docker image with extended support token setup.
https://github.com/wpengine/server-cm/pull/10620/files
> [IED-1470] Updating to use golden bionic docker image
